### ISSUE TITLE
Increase coverty of numericalAnalysis.cpp to 100%

### ISSUE THREAD

**Issue by OpusV** [Mantella/Mantella#172]
```c++
if (std::abs(previousUpperBoundObjectiveValue) <= std::abs(upperBoundObjectiveValue)) {
  stepSize = middleOfBounds;
...
```
numericalAnalysis.cpp: If-statement in line 66 is never getting true, so line 67 (`stepSize = middleOfBounds;`) is not covered by testNumericalAnalysis.cpp

**Comment by OpusV** [comment]
I tried functions e.g. (x-1)(x+1)² + 2 or (1 / 1000)(x-50)(x+50)² + 250 (flatter...), but I didn't catch the if-body described in the previous post. I'll get in touch with this issue later

**Comment by SebastianNiemann** [comment]
Done by #217

**Comment by SebastianNiemann** [comment]
Wit the complete overhaul in #217, this is not necessary anymore.
