### ISSUE TITLE
Add a develop branch

### ISSUE THREAD

**Issue by SebastianNiemann** [Mantella/Mantella#237]
When this is done, we work with each branch as described in _git flow_, except that we will not have release branches.

**Comment by SebastianNiemann** [comment]
It think this will not be necessary before version 1.0.0, as the master branch is no tag yet.

@OpusV What are your toughs on this?

**Comment by OpusV** [comment]
After a few thoughts I agree. First tag should be _v1.0_ and the develop branch is not necessery so far.
