### ISSUE TITLE
Add SQLite-Database

### ISSUE THREAD

**Issue by OpusV** [Mantella/Mantella#241]
Creating a database to save learned data from HINT-based optimisation. Databse could be Redis [Redis Page](http://redis.io/).

**Comment by SebastianNiemann** [comment]
After evaluating our options, I vote for SQLite instead of Redis, as it better fits to our current use-case.

**Comment by SebastianNiemann** [comment]
After thinking about how to retrieve elitists without hurting our performance, I got the following idea.

As of now, we have a single function handling the optimisation process and good reasons to change to this recently. Therefore, simply extending the previous loop to retrieve the elitists is not an option anymore.

However, we can still extend our wrapper around the objective function to handle this.

A drawback would be, that we will have some upper limit on how many

**Comment by SebastianNiemann** [comment]
This is not planned for Mantella anymore
