### ISSUE TITLE
find and compare alternatives for TravisCI

### ISSUE THREAD

**Issue by pschiffmann** [Mantella/Mantella#396]
We currently face two problems with TravisCI: Their servers are often at full capacity, resulting in slow build times; and their latest ubuntu image (trusty) is quite old already.

**Comment by SebastianNiemann** [comment]
An hour ago (between 6-7 o'clock, MEZ), Travis CI was working *OK* (but not perfect, compared to AppVeyor).

Now (7:30 o'clock, MEZ), our builds got delayed again ... for no reason, as the status page reports that Travis CI has no jobs in its backlog and yet to hit the maximal number of jobs to process simultaneously...
