### ISSUE TITLE
simplify random distribution boundaries

### ISSUE THREAD

**Issue by pschiffmann** [Mantella/Mantella#418]
Some functions do the following when drawing a random value from a range `min, max`:

```random_value = min + std::uniform_real_distribution<T>(0, 1)(random_number_generator()) * (max - min);```

which can be shortened to:

```random_value = std::uniform_real_distribution<T>(min, max)(random_number_generator());```

**Comment by SebastianNiemann** [comment]
Thanks, this seems to be a leftover from a time where `min` and `max` could have been representing multiple elements.
